" Various
language en_US.UTF-8
set incsearch
set showmatch
set mouse=a
set autoindent
set copyindent
set nobackup
"set listchars+=nbsp:¬

" Highlight current line
set cursorline
au WinLeave * set nocursorline
au WinEnter * set cursorline

" Line numbers and cursor position
set ruler
set numberwidth=1
set number
hi LineNr cterm=inverse
hi CursorLine cterm=NONE
hi CursorLine ctermbg=LightBlue

" Indentation
set autoindent
